# ==========================================
# Environment
# ==========================================
environment: "debug"
production: "debug"

# ==========================================
# Logging
# ==========================================
log_level: "staging"

# ==========================================
# Features
# ==========================================
features_enabled: false