# ==========================================
# Environment
# ==========================================
environment: "debug"

# ==========================================
# Logging
# ==========================================
log_level: "debug"

# ==========================================
# Features
# ==========================================
features_enabled: false